FIX: import from correct mpl backend by qt version
MatthieuDartiailh/enaml pull request #14
Opened 2017-04-05 19:58 UTC by tacaswell

This enable enaml + matplotlib to work with pyqt5.

2017-04-06 09:24 UTC, MatthieuDartiailh requested changes
Some minor changes otherwise LGTM

2017-04-06 09:24 UTC, MatthieuDartiailh commented on enaml/qt/qt_mpl_canvas.py
> +from .QtCore import Qt, PYQT_VERSION_STR
PYQT_VERSION_STR is unused so please remove it. Also you can avoid importing QT_VERSION from qtpy by importing __version__ or __version_info__ (tuple of int) from .QtCore which I would prefer.

2017-04-06 09:24 UTC, MatthieuDartiailh commented on enaml/qt/qt_mpl_canvas.py
> +    raise RuntimeError('Using qtpy.QT_VERSION == {} which we do not know how '
Here I find the message a bit confusing. I would say: 
```python
"No known Matplotlib backend for qt version {__version__} (as reported by qtpy.QT_VERSION)"
```
I am not convinced mentioning qtpy here really helps but I am not opposed to keeping the mention

2017-04-06 12:00 UTC, tacaswell commented on enaml/qt/qt_mpl_canvas.py
> +from .QtCore import Qt, PYQT_VERSION_STR
Are those the version of qt or of the wrapper?

2017-04-06 14:52 UTC, MatthieuDartiailh commented on enaml/qt/qt_mpl_canvas.py
> +from .QtCore import Qt, PYQT_VERSION_STR
Actually \_\_version\_\_ is just an alias of QT_VERSION exported by .QtCore

2017-05-30 10:50 UTC, MatthieuDartiailh commented
@tacaswell do you have time to address the minor comments ?

2017-06-13 08:57 UTC, MatthieuDartiailh commented
ping @tacaswell

2017-06-22 02:15 UTC, tacaswell commented
Sorry, this got buried at the bottom of my 2.4k notifications :disappointed: 

Fixed and force-pushed.

2017-06-22 06:56 UTC, MatthieuDartiailh approved these changes

2017-06-22 06:57 UTC, MatthieuDartiailh commented
Thanks @tacaswell merging now. I will try to get a fix for qt console and I will release a new version afterwards.

2017-06-22 06:57 UTC, merged

2017-06-22 07:33 UTC, MatthieuDartiailh commented
@tacaswell I get that you are awfully busy but you may be interested in doing a quick review of the PR opened on this repo as they may be of interest to you, and I would really appreciate it.

2017-06-26 19:00 UTC, tacaswell commented
Any in particular or just in general?

2017-06-26 20:56 UTC, MatthieuDartiailh commented
I though about the one about the qtconsole that I merged two days ago, in case you are familiar with it ? Otherwise I would really like some feedback on the setup commands. I need to improve the documentation about how to use it in a way allowing setuptools to install enaml before it is needed by the package, but otherwise I think it would be a nice improvement.
I think I will make a new release with the matplotlib fix, the ipython fix and the setup improvement once it is merged.